import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dbConnect } from "@/lib/mongo";
import ThemeContextProvider from "@/context/theme.context-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const db = await dbConnect();

  return (
    <html lang="en">
      <ThemeContextProvider>
        <body className={`${inter.className} dark:bg-black bg-white `}>{children}</body>
      </ThemeContextProvider>
    </html>
  );
}
