import { Toaster } from "react-hot-toast";
import Navbar from "../components/dashboard/navbar";
import ThemeSwitchButton from "../components/theme.switch";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <div className="">
          {/* <div
            className="bg-[#fbe2e3] absolute top-[-6rem] right-[11rem] h-[31.25rem] w-[50rem]
                        rounded-full blur-[10rem] sm:w-[68.75rem] md:left[-33rem] lg:left[-28rem]
                        2xl:left[-5rem] -z-10"
          ></div>

          <div
            className="bg-[#dbd7fb] absolute top-[-1rem] left-[-35rem] h-[31.25rem] w-[50rem]
                        rounded-full blur-[10rem] sm:w-[68.75rem] md:left[-33rem] lg:left[-28rem]
                        2xl:left[-5rem] -z-10
        
        "
          ></div> */}

          <div className="absolute top-[50px] inset-0 justify-center inline-flex flex-row -z-[9999]">
            <div className="absolute top-[50px] inset-0 justify-center inline-flex flex-row ">
              <div className="dark:bg-white bg-black opacity-[.5] bg-blur filter blur-[90px] w-[400px] h-[400px] rounded-[9999px]  relative animate-one"></div>
              <div className="bg-light-purple opacity-[.5] bg-blur filter blur-[90px] w-[400px] h-[400px] rounded-[9999px]  relative animate-two "></div>
              <div className="dark:bg-white bg-black opacity-[.5] bg-blur filter blur-[90px]  w-[400px] h-[400px] rounded-[9999px]  relative animate-three"></div>
            </div>
          </div>
          <Navbar />
          {children}
          <ThemeSwitchButton/>
          <Toaster position="bottom-left" />
        </div>
      </body>
    </html>
  );
}
